In [3]:
import numpy as np

In [4]:
#one dimination array
a = np.array([2,6,9])
a[0]
a[2]
a.ndim    #It is used to check dimension of an array 

1

In [5]:
#2-D array
a2 = np.array([[1,2],[3,4],[5,6]])
a2.ndim
a2.itemsize   # its size of item since int have 4 bit size so output will be 4
a2.dtype       #to check datatype
  
# here we change datatype into float from int 
a2=np.array([[1,2,3],[5,6,7]] ,dtype=np.float64)
a2.dtype
a2
a2.size #total number of elements
a2.shape  #dimension of 2D array (rows , coloum )

# here we change datatype into complex from int 
a2=np.array([[1,2,3],[5,6,7]] ,dtype=complex)
a2
a2.shape

(2, 3)

In [6]:
a = np.zeros((3,4))
a
a = np.ones((10,3))
a

#for range 
np.arange(1,9)
np.arange(1,19,2)
np.linspace(1,5,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ])

In [7]:
a=np.array([[1,2],[4,6],[9,2],[12,65]])
a
a.shape
a.reshape(2,4)  # It is used to change diminsion of array 
a.ravel()  #It will make one dimsion array

array([ 1,  2,  4,  6,  9,  2, 12, 65])

In [8]:
a=np.array([[1,2],[4,6],[9,2],[12,65],[345,32]])
a
a.min()
a.max()
a.sum()

#axis 1 is used for rows 
#axis 0 is used for coloums
a.sum(axis=0)
a.sum(axis=1)

array([  3,  10,  11,  77, 377])

In [9]:
a=np.arange(1,6)
a
np.sqrt(a)
np.std(a) #standard devisionb

1.4142135623730951

In [16]:
a=np.array([[3,4],[1,2]])
b=np.array([[9,8],[7,1]])
a+b
a/b
a*b
a.dot(b)  # matrics product


array([[55, 28],
       [23, 10]])