In [1]:
import numpy as np

In [5]:
#Slicing using list
n = [1,2,3,4,5]
n[0:3]
n[-1]

#Slicing using numpy 
a=np.array([6,7,8,1,3])
a[0:3]
a[-1]

a=np.array([[4,5,6],[1,2,3],[9,8,7]])
a[1,2]
a[0:2,2]  #0:2 represent rows and ,2 represent col.
a[-1] #last row will be printed
a[-1,0:2] 
a[:,1:3]
a[0:2,1:3]

array([[5, 6],
       [2, 3]])

In [12]:
a=np.array([[4,5,6],[1,2,3],[9,8,7]])
a
for rows in a:
    print(rows)

for cell in a.flat:
    print(cell)

[4 5 6]
[1 2 3]
[9 8 7]
4
5
6
1
2
3
9
8
7


In [24]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
a
b
np.vstack((a,b))
np.hstack((a,b))


a=np.arange(30).reshape(2,15)
a
np.hsplit(a,3)
result = np.hsplit(a,3) #slpliting given list into 3 parts
result[0]
result[1]
result[2]


array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [31]:
a=np.arange(12).reshape(3,4)
a
b= a>4
b
a[b]
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])